### ISSUE TITLE
Latest cpinutil.py and explicit solvent messages?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-constph#14]
I realize we're using a possibly-outdated version of [`cpinutil.py`]() for our current tests.

@swails: Where should we get the most up-to-date version of this tool?

Also, I'm wondering what this warning means:
```
Warning: Carboxylate residues in explicit  solvent simulations require a modified
topology file! Use the -op flag to print one.
```

**Comment by swails** [comment]
> I realize we're using a possibly-outdated version of cpinutil.py for our current tests.

I actually dumped it in ParmEd.  The `parmed/amber/titratable_residues.py` has the definitions for all of the titratable residues, their charge vectors, and their reference energies.  The driver script itself is in the `test/` directory to ensure coverage of `titratable_residues.py`

> Also, I'm wondering what this warning means:

Irrelevant for your uses.  Explicit solvent uses GB for the proton exchanges, and to get that working I had to reduce the solvation radii for the carboxylate oxygens (which required writing a new topology file).  Since you're not using GB in explicit solvent for the proton exchanges, this doesn't apply (but that also means that the reference energies *also* don't apply).

**Comment by bas-rustenburg** [comment]
I've actually been using the version included in AmberTools14 to generate new cpin files, which is working fine for me so far.

**Comment by swails** [comment]
Yes, there should be no real difference.

**Comment by jchodera** [comment]
OK.  We should either expunge the old version in this repo and document that (or better yet, get `cpinutil` into `ambermini`) or pull in the latest version.

**Comment by bas-rustenburg** [comment]
For now, we're using ambertools.
